apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-exercise-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-exercise
      tier: backend
  template:
    metadata: 
      labels:
        app: kubernetes-exercise
        tier: backend
    spec: 
      containers:
        - name: api
          image: whitequbits/kubernetes-exercise:latest
